### ISSUE TITLE
Plate missing

### ISSUE THREAD

**Issue by persocon** [VinnyCordeiro/TEK-80#1]
you forgot the plate haha.
ALSO HUGE THANKS FOR UPLOADING THIS <3 you have no IDEA how it will help me!

**Comment by VinnyCordeiro** [comment]
No, I didn't. The plate is the DXF file, as it is meant for a laser cutter (or other technology) to make it out of a sheet of metal and most companies out there accept DXF files for that. No need for a 3D model of a inherently 2D part. :)

E sim, eu fiz o upload depois de ler teu comentário lá no Geekhack. <3 Se for fazer um para ti, vou querer um para mim também, eu pago os custos de material e mão-de-obra.

**Comment by persocon** [comment]
Não era bem o plate aonde vão as teclas, qdo abri o assembly, ele disse que tinha um plate faltando, acredito que seja aquele em cobre que o Photekq fez que tinha GeekHack escrito e tals que vai no fundo do Base.

---
Então, provavelmente eu vá fazer em 3D, tem um amigo meu que tá com uma impressora e vai imprimir umas coisas pra mim já, até já converti os CADs pra STL, aí falta recortar em 3 partes senão não cabe na mesa lá da impressora, vc tá no Discord lá que a galera do Reddit fez? se sim me dá um ping depois por lá @tkrp1986#6417

**Comment by VinnyCordeiro** [comment]
Ah, tá, agora entendi. Eu fiz o upload de todos os arquivos que estavam disponíveis na época, então este está faltando. Alguém que saiba usar o Solidworks deve ser capaz de recriar essa peça.
